### ISSUE TITLE
Terminal API doesn't work for a plugin running in a sidecar container

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che-theia#112]
### Description
[Theia Plugin Terminal API](https://github.com/theia-ide/theia/blob/b21023ef38060a127b0c152bdf71344de8950f59/packages/plugin/src/theia.d.ts#L3126) doesn't work for a plugin running in a sidecar container.

### Reproduction Steps
1/ Start Che Workspace with the [terminal-plugin sample](https://github.com/eclipse/che-theia-samples/tree/master/samples/terminal-plugin) running in its own container.
Use the DevFile:
```yaml
specVersion: 0.0.1
name: terminal-sample
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: terminal-sample-plugin
    type: chePlugin
    id: https://raw.githubusercontent.com/azatsarynnyy/che7-plugin-registry/master/terminal-sample:0.0.1

```
2/ Call the `Send text to the terminal` command from Theia Command Palette.

#### Expected behavior:
New Terminal is created and text is printed to the terminal
![image](https://user-images.githubusercontent.com/1636395/54398444-be311c00-46c2-11e9-96dd-c38e9cb460a7.png)

#### Diagnostics:
from browser's console:
```
Uncaught (in promise) TypeError: Cannot read property 'proxy' of undefined
    at TerminalServiceExtImpl.createTerminal (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/terminal-ext.js:77)
    at TerminalServiceExtImpl.createTerminal (/home/theia/lib/node/terminal-container-aware.js:43)
    at Object.createTerminal (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:299)
    at createTerminalWithOptions (/plugins/terminal-sample.0.0.1/lib/new-terminal-backend.js:262)
    at /plugins/terminal-sample.0.0.1/lib/new-terminal-backend.js:106
    at /home/theia/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:113
    at CommandRegistryImpl.executeLocalCommand (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:165)
    at CommandRegistryImpl.$executeCommand (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:130)
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:175)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:160)
```
