### ISSUE TITLE
task/che-commands should not ask the target machine (component) if already defined in devfile

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#154]
### Description
It looks like a regression, when i define che-commands with a target machine (component) in a devfile, Running the task is still asking which machine to use:

### Reproduction Steps
Run this devfile:

```yaml
# A devfile to setup sunix-devfiles repo
#

specVersion: 0.0.1
name: sunix-devfiles
projects:
  - name: devfiles
    source:
      type: git
      location: 'https://github.com/sunix/devfiles.git'
components:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:next
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: git
    type: dockerimage
    image: sunix/git-devtools
    mountSources: true
    memoryLimit: 256M
  - name: theia-endpoint-runtime
    type: dockerimage
    image: eclipse/che-theia-endpoint-runtime:nightly
    endpoints:
      - name: theia-remote-endpoint
        port: 10000
        attributes:
          protocol: ws
          public: 'true'
    memoryLimit: 512M
    mountSources: true
  - name: vscode-yaml
    type: chePlugin
    id: redhat.vscode-yaml:0.3.0
commands:
  - name: run on git
    actions:
      - type: exec
        component: git
        command: pwd

  - name: run on theia-editor
    actions:
      - type: exec
        component: theia-editor
        command: pwd

```
run the command `run on theia-editor` it is supposed to run that on the theia-editor container but it is still asking where to run it.
On another side, `run on git` works well

**OS and version:**    
Minikube - che7 started with chectl
