### ISSUE TITLE
running a task/che-commands is showing error: `Request {taskname} failed with error: Information not found`

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#155]
### Description
When trying to run a che-command, `Request {taskname} failed with error: Information not found` message is display and the command is not executed

### Reproduction Steps
Run this devfile:

```yaml
specVersion: 0.0.1
name: sunix-devfiles
projects:
  - name: devfiles
    source:
      type: git
      location: 'https://github.com/sunix/devfiles.git'
components:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:next
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: git
    type: dockerimage
    image: sunix/git-devtools
    mountSources: true
    memoryLimit: 256M
  - name: theia-endpoint-runtime
    type: dockerimage
    image: eclipse/che-theia-endpoint-runtime:nightly
    endpoints:
      - name: theia-remote-endpoint
        port: 10000
        attributes:
          protocol: ws
          public: 'true'
    memoryLimit: 512M
    mountSources: true
  - name: vscode-yaml
    type: chePlugin
    id: redhat.vscode-yaml:0.3.0
commands:
  - name: run
    actions:
      - type: exec
        component: git
        command: pwd

```
run the command `run` it is supposed to execute the command `pwd` but it is not and showing in a dialog box: `Error launching task 'run': Request run failed with message: Information not found`

and in theia ide logs:
```
root ERROR Request run failed with error: Information not found Error: Information not found
    at CheTask.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-task-service.js:216:35)
    at step (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-task-service.js:54:23)
    at Object.next (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-task-service.js:35:53)
    at fulfilled (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-task-service.js:26:58)
    at <anonymous>
task ERROR Error launching task 'init ... che-theia': Request run failed with message: Information not found
```

**OS and version:**    
Minikube - che7 started with chectl
