### ISSUE TITLE
Make it possible to add a VSCode extension

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che-theia#209]
We need a way to be able to simply install a VS Code extension.

First step:
  - [ ] User should be able to pick a plugin from VS Code Marketplace Site and install it in Che Theia
  - [ ] User should be able to drag and drop 'Install' button from VS Code marketplace to the Plugins view

Following improvements:
  - [ ] Display list of installed VS Code plugins in dedicated list
  - [ ] User should be able to pick a VS Code plugin using Plugins view and install it by clicking 'Install' button

For the first step is enough to open https://marketplace.visualstudio.com/, find a plugin, copy its id and install by running a special command in Theia.

To persist installed plugins we need to download vscode plugins in dedicated directory and add this directory to volumes
```
   env:
       - name: THEIA_PLUGINS
         value: local-dir:///plugins,local-dir:///vscode-plugins
       - name: VSCODE_PLUGINS
         value: local-dir:///vscode-plugins
   volumes:
       - mountPath: "/plugins"
         name: plugins
       - mountPath: "/vscode-plugins"
         name: vscode-plugins
```
