### ISSUE TITLE
My workspace view empty if no user defined container

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#214]
### Description
The workspace view completely empty if no user runtime has been define in the container view.
Also a error appear `[object Object]`

![Selection_244](https://user-images.githubusercontent.com/650571/57509937-ca71d800-7305-11e9-87d4-0f2cef59480f.png)
with the devfile:
```yaml
specVersion: 0.0.1
name: chectl
projects:
  - 
    name: chectl
    source:
      type: git
      location: 'https://github.com/che-incubator/chectl.git'

components:
  - 
    id: eclipse/che-theia/next
    type: cheEditor
  - 
    id: eclipse/che-machine-exec-plugin/0.0.1
    type: chePlugin
  - 
    id: redhat/vscode-yaml/0.4.0
    type: chePlugin
  - 
    alias: ts
    id: che-incubator/typescript/1.30.2
    type: chePlugin

commands:
  - name: build
    actions:
      - type: exec
        component: ts
        command: yarn
        workdir: /projects/chectl
  - name: test
    actions:
      - type: exec
        component: ts
        command: yarn test
        workdir: /projects/chectl
```
But once we add a dockerimage component:
![Selection_235](https://user-images.githubusercontent.com/650571/57509922-c2199d00-7305-11e9-9c41-a7c3a8584cb0.png)
```yaml
specVersion: 0.0.1
name: chectl
projects:
  - 
    name: chectl
    source:
      type: git
      location: 'https://github.com/che-incubator/chectl.git'

components:
  - 
    id: eclipse/che-theia/next
    type: cheEditor
  - 
    id: eclipse/che-machine-exec-plugin/0.0.1
    type: chePlugin
  - 
    alias: git-devtools
    type: dockerimage
    image: sunix/git-devtools
    mountSources: true
    memoryLimit: 256M
  - 
    id: redhat/vscode-yaml/0.4.0
    type: chePlugin
  - 
    alias: ts
    id: che-incubator/typescript/1.30.2
    type: chePlugin

commands:
  - name: build
    actions:
      - type: exec
        component: ts
        command: yarn
        workdir: /projects/chectl
  - name: test
    actions:
      - type: exec
        component: ts
        command: yarn test
        workdir: /projects/chectl
```
