### ISSUE TITLE
che7 yaml plugin is failing to start

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#280]
### Description
starting a workspace from devfile using the yaml plugin, it is failling to start the yaml plugin with the error
```
Error - 5:48:19 PM] Starting client failed
Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:538:9)
    at Object.fork (child_process.js:113:10)
    at Object.fork (/tmp/vscode-unpacked/redhat.vscode-yaml.latest.zdyhmqlakk.redhat.vscode-yaml-0.4.0.vsix/extension/node_modules/vscode-languageclient/lib/utils/electron.js:83:23)
    at Promise (/tmp/vscode-unpacked/redhat.vscode-yaml.latest.zdyhmqlakk.redhat.vscode-yaml-0.4.0.vsix/extension/node_modules/vscode-languageclient/lib/main.js:269:34)
    at new Promise (<anonymous>)
    at LanguageClient.createMessageTransports (/tmp/vscode-unpacked/redhat.vscode-yaml.latest.zdyhmqlakk.redhat.vscode-yaml-0.4.0.vsix/extension/node_modules/vscode-languageclient/lib/main.js:249:24)
    at LanguageClient.createConnection (/tmp/vscode-unpacked/redhat.vscode-yaml.latest.zdyhmqlakk.redhat.vscode-yaml-0.4.0.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1854:21)
    at LanguageClient.resolveConnection (/tmp/vscode-unpacked/redhat.vscode-yaml.latest.zdyhmqlakk.redhat.vscode-yaml-0.4.0.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1697:44)
    at LanguageClient.start (/tmp/vscode-unpacked/redhat.vscode-yaml.latest.zdyhmqlakk.redhat.vscode-yaml-0.4.0.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1628:14)
```
![Selection_299](https://user-images.githubusercontent.com/650571/59528090-9f1e7200-8edd-11e9-9adf-78e3df7381e3.png)

### Reproduction Steps
Start with chectl the devfile:

```yaml
apiVersion: 1.0.0

metadata:
  name: fail-yaml

projects:

  - name: chectl
    source:
      type: git
      location: 'https://github.com/che-incubator/chectl.git'

components:

  - id: redhat/vscode-yaml/latest
    type: chePlugin
```

**OS and version:**    
Minikube single-user with chectl (helm)
