### ISSUE TITLE
Errors in Che Theia container log when start another instance

### ISSUE THREAD

**Issue by mmorhun** [eclipse/che-theia#299]
### Description

When start another Che Theia instance, a lot of error logs appears in the Che Theia IDE container:

```

root ERROR Request getCwdURI failed with error: terminal "1" does not exist Error: terminal "1" does not exist
  at ShellTerminalServer.<anonymous> (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:117:27)
  at step (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:59:23)
  at Object.next (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:40:53)
  at /home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:34:71
  at new Promise (<anonymous>)
  at __awaiter (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:30:12)
  at ShellTerminalServer.BaseTerminalServer.getCwdURI (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:112:16)
  at JsonRpcProxyFactory.<anonymous> (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:217:73)
  at step (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:47:23)
  at Object.next (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:28:53)
```
The error is repeated many times.

### Reproduction Steps

1. Create Che Theia dev workspace from the following devfile:
<details>
<summary>Devfile</summary>

```yaml
metadata:
  name: wksp-theia
projects:
  - name: theia
    source:
      location: 'https://github.com/theia-ide/theia.git'
      type: git
      branch: master
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
components:
  - mountSources: true
    id: che-incubator/typescript/latest
    memoryLimit: 2048Mi
    type: chePlugin
  - mountSources: true
    type: dockerimage
    memoryLimit: 3072Mi
    image: 'eclipse/che-theia-dev:next'
apiVersion: 1.0.0
```
</details>

2. Init and build Che Theia
3. Keep at least one terminal open in main Theia
4. Start another instance, which had been just built with command: `yarn theia start --hostname=0.0.0.0 --port=3130`
5. See `theia-ide` container logs.
