### ISSUE TITLE
how to run che-theia?

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse/che-theia#335]
I run theia, and run che,but how to run che-theia by source?

**Comment by olexii4** [comment]
It is a long way. After all changes, the target image should be built and using for CHE.   
Look into **che-theia/dockerfiles**. 
For example:

[How to Build Theia Image](https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/README.md) 

Theia is an editor inside CHE. One of the editors can be added from the repository(official or custom) or by a link in the workspace defile.

The simplest way is using a URL for a custom registry.
For example:
```
metadata:
  name: wksp-88kt
components:
  - type: cheEditor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/ws-skeleton/eclipseide/4.9.0/meta.yaml
apiVersion: 1.0.0
```
It is a devfile with an editor added by URL from 
[Eclipse Che plugin registry](https://github.com/eclipse/che-plugin-registry) 

Look into to understand how to create a custom editor with your own image.

So, you can do next:
1. Build the target image and push to upstream.
2. Create a custom editor(just meta.yaml).
3. Create a devfile with a reference for the editor.
