### ISSUE TITLE
Remote plugin isn't registered in Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che-theia#62]
When running [Che k8s plugin](https://github.com/azatsarynnyy/che7-plugin-registry/blob/master/ms-kubernetes-tools.vscode-kubernetes-tools/0.1.16/meta.yaml) in a separate sidecar container, the plugin isn't registered in Theia.

***Steps to reproduce***
- start minikube with the command
`minikube start --memory 8192 --cpus 4 --disk-size 50g --docker-opt userland-proxy=false`
- start nightly Che Server with the command
`chectl server:start`
- start a Che workspace with the command
`chectl workspace:start -f devfile`
where `devfile` has the following content:
```yaml
specVersion: 0.0.1
name: che-k8s-plugin
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:master
  - name: k8s-plugin
    type: chePlugin
    id: https://raw.githubusercontent.com/azatsarynnyy/che7-plugin-registry/master/ms-kubernetes-tools.vscode-kubernetes-tools:0.1.16
```

There're contributions from package.json are registered (views, etc.) but no commands (with `Kubernetes:` prefix) in the Commands Palette.

***Diagnostics***
theia-ide conatiner logs:
```
$ kubectl logs workspaceqjq1fy3kkj4pppxh.che-workspace-pod-5b9db4c7bb-8ftn6 --namespace=kube-che --container=theia-ide
...
root ERROR Uncaught Exception:  Error: connect ETIMEDOUT 10.108.50.184:8413
root ERROR Error: connect ETIMEDOUT 10.108.50.184:8413
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
root ERROR Uncaught Exception:  TypeError: Cannot read property 'aborted' of null
root ERROR TypeError: Cannot read property 'aborted' of null
    at ClientRequest.req.on (/home/theia/node_modules/ws/lib/websocket.js:531:19)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketCloseListener (_http_client.js:377:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
root INFO Notification handler 'onMessage' failed with message: WebSocket is not open: readyState 2 (CLOSING)
...
```

plugin conatiner logs
```
$ kubectl logs workspaceqjq1fy3kkj4pppxh.che-workspace-pod-5b9db4c7bb-8ftn6 --namespace=kube-che --container=pluginsidecarmewvgz -f
Plugins Endpoints are  [ 'ws://opuzjilvbz:8413' ]
Plugins Mapping Endpoints are  Map {
  'ms_kubernetes_tools_vscode_kubernetes_tools' => 'ws://opuzjilvbz:8413' }
Starting the deployer with the list of resolvers [ LocalDirectoryPluginDeployerResolver {},
  GithubPluginDeployerResolver { unpackedFolder: '/tmp/github-remote' },
  HttpPluginDeployerResolver { unpackedFolder: '/tmp/http-remote' },
  VsCodePluginDeployerResolver { unpackedFolder: '/tmp/vscode-extension-marketplace' } ]
Theia Endpoint 1/pid listening on port 8413
Found the list of default plugins ID on env: undefined
Found the list of plugins ID on env: undefined
```
